name: NeoMag CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Frontend Dependencies
        run: npm install

      # Gelecek Adım: Lint ve Test
      # - name: Run Linter
      #   run: npm run lint
      # - name: Run Tests
      #   run: npm run test

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install Backend Dependencies
        run: pip install -r requirements.txt
        
      - name: Run Backend Tests
        run: python -m pytest tests
        env:
          PYTHONPATH: .

      # Gelecek Adım: Lint ve Test
      # - name: Run Linter
      #   run: flake8 .
      # - name: Run Tests
      #   run: pytest 